---
title: "Trend"
output:
  html_document:
    df_print: paged
---

```{r}
library(stats)
suppressPackageStartupMessages(
  library(fpp2)
)
library(forecast)
suppressPackageStartupMessages(
  library(dynlm)
)
library(magrittr)
suppressPackageStartupMessages(
  library(tseries)
)
```

```{r}
L=read.csv('LaborForce.csv',header=T)

Labor = ts(L$LNU01327662,start=1992,frequency=12)

autoplot(Labor,main="US Labor Force Participation Rate",ylab="Percent",xlab="Year")

acf(Labor)
pacf(Labor)
t = time(Labor)
```


```{r}
model1=dynlm(Labor~t)
plot1=ts(predict(model1),start=1992,frequency=12)
autoplot(plot1)+autolayer(Labor)


model2=dynlm(Labor~t+sin(2*pi*t/13)+cos(2*pi*t/13))
plot2=ts(predict(model2),start=1992,frequency=12)
autoplot(plot2) + autolayer(Labor)

model3=dynlm(Labor~t+I(t*cos(2*pi*t/15))+I(t*sin(2*pi*t/15)))
plot3=ts(predict(model3),start=1992,frequency=12)
autoplot(plot3) + autolayer(Labor)


model4=dynlm(Labor~t+sin(2*pi*t/13)+t*cos(2*pi*t/13))
plot4=ts(predict(model4),start=1992,frequency=12)
autoplot(plot4) + autolayer(Labor)

model5=dynlm(Labor~t+sin(2*pi*t/14)+t*cos(2*pi*t/14))
plot5=ts(predict(model5),start=1992,frequency=12)
autoplot(plot5) + autolayer(Labor)

model6=dynlm(Labor~t+cos(2*pi*t/12))
plot6=ts(predict(model6),start=1992,frequency=12)
autoplot(plot6) + autolayer(Labor)

model7=dynlm(Labor~t+t*cos(2*pi*t/15)+t*sin(2*pi*t/15))
plot7=ts(predict(model7),start=1992,frequency=12)
autoplot(plot7) + autolayer(Labor)

model8=dynlm(Labor~I(t*t)+t*cos(2*pi*t/13)+sin(2*pi*t/13))
plot8=ts(predict(model8),start=1992,frequency=12)
autoplot(plot8) + autolayer(Labor)
```

```{r}
t_adj=t-1992
model28=nls(Labor~a+b*t_adj+
             c*cos(2*pi*t_adj/p)+d*sin(2*pi*t_adj/p)+
             e*t_adj*cos(2*pi*t_adj/p)+f*t_adj*sin(2*pi*t_adj/p)+
             g*cos(4*pi*t_adj/p)+h*sin(4*pi*t_adj/p)+
             i*t_adj*cos(4*pi*t_adj/p)+j*t_adj*sin(4*pi*t_adj/p),
           start=data.frame(a=82,b=-0.29,p=14,
                            c=-0.0934,d=0.28,
                            e=0.031317,f=-0.035067,
                            g=0.01,h=0.01,
                            i=0.01,j=0.01))
plot28=ts(predict(model28),start=1992,frequency=12)
autoplot(plot28) + autolayer(Labor)
```

```{r}
t_adj=t-1992
model29=nls(Labor~a+b*t_adj+
             c*cos(2*pi*t_adj/p)+d*sin(2*pi*t_adj/p)+
             e*t_adj*cos(2*pi*t_adj/p)+f*t_adj*sin(2*pi*t_adj/p)+
             g*cos(4*pi*t_adj/p)+h*sin(4*pi*t_adj/p),
           start=data.frame(a=82,b=-0.29,p=14,
                            c=-0.0934,d=0.28,
                            e=0.031317,f=-0.035067,
                            g=0.01,h=0.01))
plot29=ts(predict(model29),start=1992,frequency=12)
autoplot(plot29) + autolayer(Labor)
```

```{r}
t_adj=t-1992
model30=nls(Labor~a+b*t_adj+
             c*cos(2*pi*t_adj/p)+
             e*t_adj*cos(2*pi*t_adj/p)+
             g*cos(4*pi*t_adj/p),
           start=data.frame(a=82,b=-0.29,p=14,
                            c=-0.0934,
                            e=0.031317,
                            g=0.01))
plot30=ts(predict(model30),start=1992,frequency=12)
autoplot(plot30) + autolayer(Labor)
```

```{r}
model31=dynlm(Labor~t+
                t*cos(2*pi*t/15.3)+t*sin(2*pi*t/15.3)+
                cos(4*pi*t/15.3)+sin(4*pi*t/15.3))
plot31=ts(predict(model31),start=1992,frequency=12)
autoplot(plot31) + autolayer(Labor)
```


```{r}
summary(model1)
summary(model2)
summary(model3)
summary(model4)
summary(model5)
summary(model6)
summary(model7)
summary(model8)
summary(model28)
summary(model29)
summary(model30)
summary(model31)

AIC(model1,model2,model3,model4,model5,model6,model7,model8,
    model28,model29,model30,model31)
BIC(model1,model2,model3,model4,model5,model6,model7,model8,
    model28,model29,model30,model31)
```

```{r}
checkresiduals(model1)
checkresiduals(model2)
checkresiduals(model3)
checkresiduals(model4)
checkresiduals(model5)
checkresiduals(model6)
checkresiduals(model7)
checkresiduals(model8)

checkresiduals(model28)
checkresiduals(model29)
checkresiduals(model30)
checkresiduals(model31)
```

